language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: xenial
    services:
      - docker
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - deadsnakes
        packages:
          - g++-7
          - cmake
          - ninja-build
          - python3.7
          - python3.7-dev
      homebrew:
        packages:
          - pyenv
    env:
      - PYTHON=3.7
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - CC=gcc-7
      - CXX=g++-7

  - os: linux
    dist: xenial
    services:
      - docker
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - deadsnakes
        packages:
          - g++-7
          - cmake
          - ninja-build
          - python3.8
          - python3.8-dev
      homebrew:
        packages:
          - pyenv
    env:
      - PYTHON=3.8
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - CC=gcc-7
      - CXX=g++-7

before_install:
  - |
    PY=python
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ $(echo "$PYTHON" | grep "^3\.") ]; then
        PY=python${PYTHON}
        curl https://bootstrap.pypa.io/get-pip.py | sudo -H $PY
      fi
    fi
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pyenv install $PYTHON
      PY=/Users/travis/.pyenv/versions/${PYTHON}/bin/python
    fi
    echo "$PY"
    PIP="$PY -m pip"
    sudo -H $PIP install --upgrade pip

install:
  - $PIP install -r requirements-dev.txt
before_script:
  - $PY --version
  - $PY setup.py build_ext --inplace
  - ldd vinum_lib.cpython-37m-x86_64-linux-gnu.so
script:
  - pytest --cov=vinum vinum/tests
after_success:
  - bash <(curl -s https://codecov.io/bash)