language: generic
compiler: clang
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-dev.txt
before_script:
  - python setup.py build_ext --inplace
script:
  - pytest --cov=vinum vinum/tests
after_success:
  - bash <(curl -s https://codecov.io/bash)