name: Coverage

on:
  push:
      branches:
        - main
jobs:
  upload_test_coverage:
    name: Upload test converage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Build
        run: |
          python setup.py build_ext --inplace

      - name: Test with pytest
        run: |
          python -m pytest --cov=vinum vinum/tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
